### ISSUE TITLE
Error: Route <attachment>

### ISSUE THREAD

**Issue by gerard2p** [nodemailer/wildduck#14]
Hello, i'm trying to receive a message form my outlook account and the server actually receives it; but when  i try to access the mail via HTTP API i get this error:

```
/root/wildduck/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Route <attachment> is missing parameter <attachment>
    at pathItem (/root/wildduck/node_modules/restify/lib/router.js:229:19)
    at String.replace (<anonymous>)
    at Router.render (/root/wildduck/node_modules/restify/lib/router.js:247:22)
    at db.users.collection.findOne (/root/wildduck/lib/api/messages.js:498:36)
    at handleCallback (/root/wildduck/node_modules/mongodb/lib/utils.js:120:56)
    at /root/wildduck/node_modules/mongodb/lib/collection.js:1417:5
    at handleCallback (/root/wildduck/node_modules/mongodb/lib/utils.js:120:56)
    at /root/wildduck/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/root/wildduck/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (/root/wildduck/node_modules/mongodb-core/lib/cursor.js:682:5)
```

this is the JSON data i can get if look for all the emails

```JSON
{
"id": 4,
"mailbox": "5980ad36f936e433e509ea39",
"thread": "598167d53342b5742b6a4943",
"from": {
"address": "gerard2perez@outlook.com",
"name": "Gerardo Pérez Pérez"
},
"subject": "Mail de Prueba",
"date": "2017-08-02T05:49:07.000Z",
"intro": "Hola Mundo",
"attachments": false,
"seen": false,
"deleted": false,
"flagged": false,
"draft": false,
"url": "/users/5980ad36f936e433e509ea38/mailboxes/5980ad36f936e433e509ea39/messages/4"
}
```

I'm using default configuration, and as suggested I'm using haraka, (also with default configuration), with queue set to queue/lmtp.

I hope, yoy can give a hint to find a solution. Thanks!

**Comment by andris9** [comment]
Thanks! I already catched this and fixed yesterday, try to upgrade your version of Wild Duck. You can also try out most of the API features with the demo web service, source [here](https://github.com/nodemailer/wildduck-webmail) (it's the same that can be found from https://wildduck.email)
