### ISSUE TITLE
sending message to oneself leads to restart error

### ISSUE THREAD

**Issue by Samicelus** [nodemailer/wildduck#41]
when trying to send email from the same email address, an error will be thrown:

TypeError: Cannot read property 'on' of undefined
at StreamCollect.Readable.pipe (_stream_readable.js:501:7)
at messageHandler.counters.ttlcounter (/root/data/www/wildduck/lib/api/submit.js:395:60)
at redis.ttlcounter (/root/data/www/wildduck/lib/counters.js:39:24)
at tryCatcher (/root/data/www/wildduck/node_modules/bluebird/js/release/util.js:16:23)
at Promise.successAdapter [as _fulfillmentHandler0] (/root/data/www/wildduck/node_modules/bluebird/js/release/nodeify.js:23:30)
at Promise._settlePromise (/root/data/www/wildduck/node_modules/bluebird/js/release/promise.js:566:21)
at Promise._settlePromise0 (/root/data/www/wildduck/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/root/data/www/wildduck/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/root/data/www/wildduck/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/root/data/www/wildduck/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/root/data/www/wildduck/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by andris9** [comment]
This is now fixed, at least somewhat - wild duck does not throw an exception anymore. It does not send a message either as sending to itself is not allowed. Not sure if such policy is needed though
