### ISSUE TITLE
Wild Duck Installer seems to configure both zone-mta and API server to the same port

### ISSUE THREAD

**Issue by fcardona** [nodemailer/wildduck#43]
I ran Wild Duck Installer on a new digitalocean droplet.

Wild Duck keeps restarting and it seems that it's because both ZoneMTA and API server are trying to use port 8080. 

```
root@test-mail-server:/var/log# lsof -i :8080
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
zone-mta: 15214 wildduck   12u  IPv4  41478      0t0  TCP localhost:http-alt (LISTEN)
```

```
Dec 22 05:57:54 test-mail-server systemd[1]: Started Wild Duck Mail Server.
Dec 22 05:57:54 test-mail-server node[18464]: info App  -----------------------------------------------------------------
Dec 22 05:57:54 test-mail-server node[18464]: info App
Dec 22 05:57:54 test-mail-server node[18464]: info App   █     █░ ██▓ ██▓    ▓█████▄    ▓█████▄  █    ██  ▄████▄   ██ ▄█▀
Dec 22 05:57:54 test-mail-server node[18464]: info App  ▓█░ █ ░█░▓██▒▓██▒    ▒██▀ ██▌   ▒██▀ ██▌ ██  ▓██▒▒██▀ ▀█   ██▄█▒
Dec 22 05:57:54 test-mail-server node[18464]: info App  ▒█░ █ ░█ ▒██▒▒██░    ░██   █▌   ░██   █▌▓██  ▒██░▒▓█    ▄ ▓███▄░
Dec 22 05:57:54 test-mail-server node[18464]: info App  ░█░ █ ░█ ░██░▒██░    ░▓█▄   ▌   ░▓█▄   ▌▓▓█  ░██░▒▓▓▄ ▄██▒▓██ █▄
Dec 22 05:57:54 test-mail-server node[18464]: info App  ░░██▒██▓ ░██░░██████▒░▒████▓    ░▒████▓ ▒▒█████▓ ▒ ▓███▀ ░▒██▒ █▄
Dec 22 05:57:54 test-mail-server node[18464]: info App  ░ ▓░▒ ▒  ░▓  ░ ▒░▓  ░ ▒▒▓  ▒     ▒▒▓  ▒ ░▒▓▒ ▒ ▒ ░ ░▒ ▒  ░▒ ▒▒ ▓▒
Dec 22 05:57:54 test-mail-server node[18464]: info App   ▒ ░ ░   ▒ ░░ ░ ▒  ░ ░ ▒  ▒     ░ ▒  ▒ ░░▒░ ░ ░   ░  ▒   ░ ░▒ ▒░
Dec 22 05:57:54 test-mail-server node[18464]: info App   ░   ░   ▒ ░  ░ ░    ░ ░  ░     ░ ░  ░  ░░░ ░ ░ ░        ░ ░░ ░
Dec 22 05:57:54 test-mail-server node[18464]: info App     ░     ░      ░  ░   ░          ░       ░     ░ ░      ░  ░
Dec 22 05:57:54 test-mail-server node[18464]: info App                       ░          ░               ░
Dec 22 05:57:54 test-mail-server node[18464]: info App
Dec 22 05:57:54 test-mail-server node[18464]: info App  ------------------------ wildduck@1.0.89 ------------------------
Dec 22 05:57:54 test-mail-server node[18464]: info App
Dec 22 05:57:55 test-mail-server node[18464]: info IMAP Secure IMAP Server listening on 0.0.0.0:993
Dec 22 05:57:55 test-mail-server node[18464]: info POP3 POP3 Server listening on 0.0.0.0:9110
Dec 22 05:57:55 test-mail-server node[18464]: info LMTP LMTP Server listening on 127.0.0.1:24
Dec 22 05:57:55 test-mail-server node[18464]: ERR! App Failed to start API server
Dec 22 05:57:55 test-mail-server node[18464]: { Error: listen EADDRINUSE 127.0.0.1:8080
Dec 22 05:57:55 test-mail-server node[18464]:     at Object._errnoException (util.js:1024:11)
Dec 22 05:57:55 test-mail-server node[18464]:     at _exceptionWithHostPort (util.js:1046:20)
Dec 22 05:57:55 test-mail-server node[18464]:     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
Dec 22 05:57:55 test-mail-server node[18464]:     at listenInCluster (net.js:1392:12)
Dec 22 05:57:55 test-mail-server node[18464]:     at doListen (net.js:1501:7)
Dec 22 05:57:55 test-mail-server node[18464]:     at _combinedTickCallback (internal/process/next_tick.js:141:11)
Dec 22 05:57:55 test-mail-server node[18464]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Dec 22 05:57:55 test-mail-server node[18464]:   code: 'EADDRINUSE',
Dec 22 05:57:55 test-mail-server node[18464]:   errno: 'EADDRINUSE',
Dec 22 05:57:55 test-mail-server node[18464]:   syscall: 'listen',
Dec 22 05:57:55 test-mail-server node[18464]:   address: '127.0.0.1',
Dec 22 05:57:55 test-mail-server node[18464]:   port: 8080 }
```

**Comment by andris9** [comment]
Oh, sorry, I recently changed some port numbers and did not verify for conflicts. I'll change the install script.

On your side you can fix this by adding the following to the end of /etc/zone-mta/zonemta.toml

```toml
[api]
# use any available port number
port=13080
```

**Comment by andris9** [comment]
This is now fixed, running the install script should yield in a working WildDuck server.

**Comment by fcardona** [comment]
Thanks!
