### ISSUE TITLE
TypeError if `session.user.id` property does not exist (due to logger)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#510]
Logging usage is causing uncaught exceptions if the `session.user` object does not conform to how the current logging practice is.

```sh
TypeError: Cannot read properties of undefined (reading 'toString')
    at IMAPConnection.handler (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/commands/append.js:135:41)
    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:287:37
    at IMAPCommand.validateCommand (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:390:9)
    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:272:18
    at IMAPCommand.append (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)
    at IMAPCommand.end (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)
    at IMAPConnection._onCommand (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-connection.js:500:28)
    at IMAPStream._readValue (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)
    at Object.readyCallback (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-stream.js:130:33)
    at PassThrough.<anonymous> (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-command.js:173:25)
```

See the code here:

<https://github.com/nodemailer/wildduck/blob/6e0b95102f681678882210df0c941c23973393b6/imap-core/lib/commands/append.js#L135>

Which could perhaps be changed to the following (and similarly elsewhere throughout the codebase):

```diff
        let logdata = {
            short_message: '[APPEND]',
            _mail_action: 'append',
            _path: path,
-            _user: this.session.user.id.toString(),
+            _user: this?.session?.user?.id ? this.session.user.id.toString() : null,
            _mailbox: this.selected.mailbox,
            _sess: this.id,
            _flags: flags.join(', '),
            _internaldate: internaldate,
            _size: raw.length
        };
```

**Comment by andris9** [comment]
Yeah, `session.user.id` is required, it's used in many places, not only for logging. So the user object should look like this:
```
{
  "id":"id-value",
  "username": "username value"
}
```
