### ISSUE TITLE
Bug: `imaptest` BAD reply for command: `search *:3: 26.32`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#538]
Curious if you know what the culprit for this might be @andris9 or if this is another non-issue?  Apologies for all the recent GH issues filed, just trying to get through this and be comfortable with test results (learning a lot too, thank you).

<img width="1146" alt="Screen Shot 2023-10-16 at 4 22 27 PM" src="https://github.com/nodemailer/wildduck/assets/101466223/6e5a2c71-4b96-4060-99c3-01c4e37177c4">

```sh
{
  short_message: 'WILDDUCK [Exception] Unexpected end of input at position 15',
  full_message: 'Error: Unexpected end of input at position 15\n' +
    '    at TokenParser.<anonymous> (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:39:23)\n' +
    '    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:83:50\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at TokenParser.<anonymous> (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:83:29)\n' +
    '    at TokenParser.getAttributes (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:87:9)\n' +
    '    at ParserInstance.getAttributes (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:648:78)\n' +
    '    at module.exports [as parser] (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:671:38)\n' +
    '    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:223:43\n' +
    '    at IMAPCommand.append (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)\n' +
    '    at IMAPCommand.end (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)',
  _exception: 'yes',
  _error: 'Unexpected end of input at position 15',
  _payload: '26.32 search *:3',
  _userId: '652ce041800914e0e7696963',
  _sess: 'jdiei6erj2343vri',
  _remoteAddress: '192.168.1.18',
  facility: 'wildduck',
  host: 'oem.local',
  timestamp: 1697491106.853,
  _component: 'wildduck'
}
```

**Comment by andris9** [comment]
This is also valid query but extremely unlikely to happen in a real life scenario. It is unlikely because you can get a far better response for the same terms by using FETCH.

**Comment by andris9** [comment]
The main issue behind these bugs is the simplistic IMAP parser that WildDuck has. It is not able to detect all kinds of corner cases - valid by the spec but not really realistic. To fix this WildDuck would need a much more sophisticated parser.

**Comment by andris9** [comment]
Closing for now. This is bug, but an acceptable one.
