### ISSUE TITLE
Bug: `imaptest` BAD Unexpected whitespace at position 14: `fetch 1,* uid`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#539]
Seems like a bug in search parsing (?)  Curious if you know what the culprit for this might be @andris9 or if this is another non-issue?

<img width="1140" alt="Screen Shot 2023-10-16 at 4 37 59 PM" src="https://github.com/nodemailer/wildduck/assets/101466223/dc3b08e3-9668-4dd6-9cb3-c8c29d4553df">

```js
                        if (this.currentNode.value !== '*' && this.currentNode.value.substr(-1) === '*' && this.currentNode.value.substr(-2, 1) !== ':') {
                          console.log('UH OH WHITESPACE 2', 'chr', chr, 'currentNode', this.currentNode);
                            throw new Error('Unexpected whitespace at position ' + (this.pos + i));
                        }
```

```sh
UH OH WHITESPACE 2 chr   currentNode <ref *1> {
  childNodes: [],
  type: 'SEQUENCE',
  value: '1,*',
  closed: true,
  parentNode: {
    childNodes: [ [Circular *1] ],
    type: 'TREE',
    value: '',
    closed: true
  },
  startPos: 11
}
{
  short_message: 'WILDDUCK [Exception] Unexpected whitespace at position 14',
  full_message: 'Error: Unexpected whitespace at position 14\n' +
    '    at TokenParser.processString (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:514:35)\n' +
    '    at new TokenParser (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:20:14)\n' +
    '    at ParserInstance.getAttributes (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:652:16)\n' +
    '    at module.exports [as parser] (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:675:38)\n' +
    '    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:223:43\n' +
    '    at IMAPCommand.append (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)\n' +
    '    at IMAPCommand.end (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)\n' +
    '    at IMAPConnection._onCommand (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-connection.js:512:28)\n' +
    '    at IMAPStream._readValue (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
    '    at IMAPStream._write (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.9/node_modules/wildduck/imap-core/lib/imap-stream.js:58:14)',
  _exception: 'yes',
  _error: 'Unexpected whitespace at position 14',
  _payload: '1.16 fetch 1,* uid',
  _userId: '652ce041800914e0e7696963',
  _sess: 'oemtdb6itsteijdh',
  _remoteAddress: '192.168.1.18',
  facility: 'wildduck',
  host: 'oem.local',
  timestamp: 1697492186.277,
  _component: 'wildduck'
}
```

<https://github.com/nodemailer/wildduck/blob/73acc42cd19af0e9fd0703d5306838f7ac5c9f17/imap-core/lib/handler/imap-parser.js#L507-L509C26>

**Comment by andris9** [comment]
Imaptest tests the corner cases of protocol support, no real email client would use such a range `1,*` - this is a valid range but not supported by WildDuck (and not by many other servers as well).

**Comment by andris9** [comment]
Closing. Acceptable bug
