### ISSUE TITLE
Bug: `Unexpected end of input at position 53` and `Invalid tag` tag errors (using Mozilla Thunderbird to copy sent message to Sent Mail folder)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#628]
Full stack trace output:

```js
{
  short_message: 'WILDDUCK [Exception] Unexpected end of input at position 53',
  full_message: 'Error: Unexpected end of input at position 53\n' +
    '    at TokenParser.<anonymous> (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:39:23)\n' +
    '    at /var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:83:50\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at TokenParser.<anonymous> (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:83:29)\n' +
    '    at TokenParser.getAttributes (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:87:9)\n' +
    '    at ParserInstance.getAttributes (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:644:78)\n' +
    '    at module.exports [as parser] (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/handler/imap-parser.js:667:38)\n' +
    '    at /var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:223:43\n' +
    '    at IMAPCommand.append (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)\n' +
    '    at IMAPCommand.end (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)\n' +
    '    at IMAPConnection._onCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-connection.js:511:28)\n' +
    '    at IMAPStream._readValue (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
    '    at Object.readyCallback (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-stream.js:130:33)\n' +
    '    at PassThrough.<anonymous> (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:173:25)\n' +
    '    at PassThrough.emit (node:events:513:28)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
  _exception: 'yes',
  _error: 'Unexpected end of input at position 53',
  _payload: '63 APPEND "Sent Mail" (\\Seen) UTF8 (~{35021}\r\nNFLZNh--',
  _userId: '646d8df00dd3cc2c6716341d',
  _sess: 'h7cwjsu27ls37hla',
  _remoteAddress: '142.147.89.236',
  _isUTF8Enabled: 'true',
  facility: 'wildduck',
  host: 'imap.forwardemail.net',
  timestamp: 1708374372.292,
  _component: 'wildduck'
}
```

and

```js
{
  short_message: 'WILDDUCK [Exception] Invalid tag',
  full_message: 'Error: Invalid tag\n' +
    '    at IMAPCommand.append (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:82:31)\n' +
    '    at IMAPCommand.end (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)\n' +
    '    at IMAPConnection._onCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-connection.js:511:28)\n' +
    '    at IMAPStream._readValue (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
    '    at next (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:185:24)\n' +
    '    at /var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:243:24\n' +
    '    at IMAPCommand.append (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)\n' +
    '    at IMAPCommand.end (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)\n' +
    '    at IMAPConnection._onCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-connection.js:511:28)\n' +
    '    at IMAPStream._readValue (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
    '    at Object.readyCallback (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-stream.js:130:33)\n' +
    '    at PassThrough.<anonymous> (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.0/node_modules/wildduck/imap-core/lib/imap-command.js:173:25)\n' +
    '    at PassThrough.emit (node:events:513:28)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
  _exception: 'yes',
  _error: 'Invalid tag',
  _responseCode: '400',
  _code: 'InvalidTag',
  _payload: ')',
  _userId: '646d8df00dd3cc2c6716341d',
  _sess: 'h7cwjsu27ls37hla',
  _remoteAddress: '142.147.89.236',
  _isUTF8Enabled: 'true',
  facility: 'wildduck',
  host: 'imap.forwardemail.net',
  timestamp: 1708374372.292,
  _component: 'wildduck'
}
```

The error happens in `imap-core/lib/imap-command.js`:

```js
            try {
                this.parsed = imapHandler.parser(this.payload, { literals: this.literals });
            } catch (E) {
```

The value of `this.payload` is:

```txt
68 APPEND "Sent Mail" (\Seen) UTF8 (~{105868}
NJLZmL--
```

The value of `this.literals` is (empty array) `[]`:

```txt
[]
```

**Comment by andris9** [comment]
Seems like a bug in Tunderbird. This APPEND syntax is valid for the UTF8=APPEND extension but WildDuck does not support this extension.

**Comment by Betterbird** [comment]
Not really. It says "... only if you have set mailnews.imap.jsmodule=true for Beta and Daily channel builds only".

Anyway, the new module doesn't work, it's got too many bugs and will be trashed. So don't use it.
