### ISSUE TITLE
Bug: iOS Apple Mail has `Invalid Idle continuation` issue

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#684]
@andris9 :wave: hope you're well.  writing in with the below issue to try to understand it more and what could possibly be causing it.  The client is using iOS mail and is receiving this error below:

```sh
{
  short_message: 'WILDDUCK [Exception] Invalid Idle continuation ("8.569 IDLE")',
  full_message: 'Error: Invalid Idle continuation ("8.569 IDLE")\n' +
    '    at IMAPConnection._nextHandler (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/commands/idle.js:26:33)\n' +
    '    at /var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-command.js:219:40\n' +
    '    at IMAPCommand.append (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-command.js:177:9)\n' +
    '    at IMAPCommand.end (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-command.js:189:14)\n' +
    '    at IMAPConnection._onCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-connection.js:511:28)\n' +
    '    at IMAPStream._readValue (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
    '    at IMAPStream._write (/var/www/production/source/node_modules/.pnpm/wildduck@1.42.1/node_modules/wildduck/imap-core/lib/imap-stream.js:58:14)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:392:12)\n' +
    '    at _write (node:internal/streams/writable:333:10)\n' +
    '    at Writable.write (node:internal/streams/writable:337:10)\n' +
    '    at TLSSocket.ondata (node:internal/streams/readable:766:22)\n' +
    '    at TLSSocket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:324:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:297:9)\n' +
    '    at Readable.push (node:internal/streams/readable:234:10)\n' +
    '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)',
  _exception: 'yes',
  _error: 'Invalid Idle continuation ("8.569 IDLE")',
  _payload: '7.569 IDLE',
  _userId: 'REDACTED',
  _sess: 'REDACTED',
  _remoteAddress: 'REDACTED',
  facility: 'wildduck',
  host: 'imap.forwardemail.net',
  timestamp: 1714384449.578,
  _component: 'wildduck'
}
```

Also around this happens they also get `WILDDUCK [Exception] STATUS not allowed now` errors.

**Comment by andris9** [comment]
WildDuck expects `DONE` from the client, but the client sends another IDLE command instead. `not allowed now` means that the account is in an invalid state. It must be 'Authenticated' or 'Selected' for STATUS.
