### ISSUE TITLE
Bug: WILDDUCK [Exception] APPEND not allowed now

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#751]
It appears that WildDuck has issues due to invalid state on a valid APPEND (post AUTH):

```sh
5|imap-993  | {
5|imap-993  |   short_message: 'WILDDUCK [Exception] APPEND not allowed now',
5|imap-993  |   full_message: 'Error: APPEND not allowed now\n' +
5|imap-993  |     '    at IMAPCommand.validateCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-command.js:387:23)\n' +
5|imap-993  |     '    at /var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-command.js:296:18\n' +
5|imap-993  |     '    at IMAPCommand.append (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-command.js:201:9)\n' +
5|imap-993  |     '    at IMAPCommand.end (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-command.js:213:14)\n' +
5|imap-993  |     '    at IMAPConnection._onCommand (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-connection.js:517:28)\n' +
5|imap-993  |     '    at IMAPStream._readValue (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-stream.js:149:14)\n' +
5|imap-993  |     '    at Object.readyCallback (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-stream.js:130:33)\n' +
5|imap-993  |     '    at PassThrough.<anonymous> (/var/www/production/source/node_modules/.pnpm/wildduck@1.45.1/node_modules/wildduck/imap-core/lib/imap-command.js:197:25)\n' +
5|imap-993  |     '    at PassThrough.emit (node:events:517:28)\n' +
5|imap-993  |     '    at endReadableNT (node:internal/streams/readable:1400:12)\n' +
5|imap-993  |     '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
5|imap-993  |   _exception: 'yes',
5|imap-993  |   _error: 'APPEND not allowed now',
5|imap-993  |   _responseCode: '500',
5|imap-993  |   _code: 'InvalidState',
5|imap-993  |   _payload: '62 append "Sent Mail" (\\Seen) UTF8 ("(* 580388B literal *)")',
5|imap-993  |   _userId: 'xxxxxxxxxxxxxx',
5|imap-993  |   _sess: 'xxxxxxxxxxxxxx',
5|imap-993  |   _remoteAddress: 'xxxxxxxxxxxxxx',
5|imap-993  |   _isUTF8Enabled: 'true',
5|imap-993  |   facility: 'wildduck',
5|imap-993  |   host: 'imap.forwardemail.net',
5|imap-993  |   timestamp: 1730193761.904,
5|imap-993  |   _component: 'wildduck'
5|imap-993  | }
```

Still trying to determine underlying culprit, if you have any thoughts let us know 🙏

**Comment by NickOvt** [comment]
Hey @titanism. Do you mind giving instruction on how to reproduce the problem? Please specify WildDuck version too.

**Comment by andris9** [comment]
Closing because can not reproduce in WildDuck
